### PR TITLE
Add delete credential for ios wrapper

### PR DESCRIPTION
**Pull request by krgko**

### CODE REVIEW

**Comment by Patrik-Stas** [comment]
@ingee Thanks for PR, the CI failed but it seems to me like some intermittent github issue. I've restarted the CI.

**Comment by mirgee** [comment]
Thank you, @krgko ! Very much appreciated. 👍

**Review by Patrik-Stas — APPROVED** [review]

**Comment by Patrik-Stas** [comment]
lgtm @mirgee  what do you think?

**Review by mirgee — APPROVED** [review]

**Comment by mirgee** [comment]
LGTM!

**Pull request merged**
